# importing the libraries 

In [161]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
# from sklearn.feature_selection import SelectKBest,chi2
from sklearn.pipeline import Pipeline,make_pipeline

In [162]:
df = pd.read_csv('TITANIC.csv')

In [163]:
df.head(8)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S

In [164]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [165]:
# splitting into training set and test sets
X_train,X_test,Y_train,Y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.3, random_state=42)

In [166]:
x_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
445       1    male   4.0      0      2  81.8583        S
650       3    male   NaN      0      0   7.8958        S
172       3  female   1.0      1      1  11.1333        S
450       2    male  36.0      1      2  27.7500        S
314       2    male  43.0      1      1  26.2500        S

In [167]:
X_test.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
709       3    male   NaN      1      1  15.2458        C
439       2    male  31.0      0      0  10.5000        S
840       3    male  20.0      0      0   7.9250        S
720       2  female   6.0      0      1  33.0000        S
39        3  female  14.0      1      0  11.2417        C

In [168]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [169]:
# Applying imputation

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [170]:
X_test_embarked.shape

(268, 1)

In [171]:
# one hot encoding Sex and Embarked

ohe_sex = OneHotEncoder(sparse_output =False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output =False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [172]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [173]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

Now, lets make numpy array

In [174]:
X_train_rem = X_train.drop(columns = ['Age','Sex','Embarked'])
X_test_rem = X_test.drop(columns = ['Age','Sex','Embarked'])

In [175]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [176]:
X_train_transformed.shape

(623, 10)

In [177]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, Y_train)

DecisionTreeClassifier()

In [178]:
Y_pred = clf.predict(X_test_transformed)

In [179]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.7611940298507462

In [180]:
# import pickle
# pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
# pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
# pickle.dump(clf,open('models/clf.pkl','wb'))

# With Using Pipeline

In [181]:
dff = pd.read_csv('titanicc.csv')

In [182]:
dff.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [183]:
dff.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [184]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [185]:
# splitting into training set and test sets
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [186]:
# imputation transformer
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [187]:
# one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [188]:
# Scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [189]:
# Feature selection
trf4 = SelectKBest(score_func=chi2,k=8)

In [190]:
# train the model
trf5 = DecisionTreeClassifier()

# Create a Pipeline

In [191]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

# Pipeline Vs Making a Pipeline

Pipeline requires naming of steps, make_pipeline does not.
(Same applies to ColumnTransformer vs make_column_transformer)

In [192]:
#let's create a Alternative Syntax here
# pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5) (for random)

In [218]:
#now, let's create a train 

# run block of code and catch warnings
with warnings.catch_warnings():
    pipe.fit(X_train, Y_train)

# Exploring the pipeline

In [194]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'trf2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse=False),
                                  [1, 6])]),
 'trf3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'trf4': SelectKBest(k=8, score_func=<function chi2 at 0x14f77f640>),
 'trf5': DecisionTreeClassifier()}

In [195]:
pipe.named_steps['trf1'].transformers_

[('impute_age', SimpleImputer(), [2]),
 ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6]),
 ('remainder', 'passthrough', [0, 1, 3, 4, 5])]

In [205]:
pipe.named_steps['trf1'].transformers_[1][1].statistics_

array(['S'], dtype=object)

In [206]:
# y Predict on features x 
y_pred = pipe.predict(X_test)

In [199]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0])

In [200]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6007462686567164

In [219]:
# cross validation
from sklearn.model_selection import cross_val_score
with warnings.catch_warnings():
    cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

In [223]:
#grid search using pipeline 
params = {
    'trf5__max_depth':[1,2,3,4,5,None]
}

In [227]:
from sklearn.model_selection import GridSearchCV
import warnings

# with warnings.catch_warnings():
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(x_train, y_train)
#cv = 5 means it splits data into train test 5 times and runs, checks to validate a model

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x14f77f640>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [228]:
grid.best_score_

0.6516516129032258

In [229]:
grid.best_params_

{'trf5__max_depth': 1}

# Exporting the pipeline

In [232]:
# exporting to web
# import pickel
# pickle.dump(pipe, open('pipe.pk1','wb'))

# Predicting Using Pipeline

In [234]:
# import pickle
# import numpy as np

# pipe = pickle.load(open('pipe.pkl','rb'))
# # Assume user input
# test_input2 = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
# pipe.predict(test_input2)

# Predicting Without Using Pipeline

In [235]:
# import pickle
# import numpy as np

# ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
# ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
# clf = pickle.load(open('models/clf.pkl','rb'))

# # Assume user input
# # Pclass/gender/age/SibSp/Parch/Fare/Embarked

# test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
# test_input
# array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)
# test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
# test_input_sex
# array([[0., 1.]])
# test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
# test_input_embarked
# array([[0., 0., 1.]])
# test_input_age = test_input[:,2].reshape(1,1)
# test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)
# test_input_transformed.shape
# (1, 10)
# clf.predict(test_input_transformed)