In [81]:
import pandas as pd
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns

In [4]:
df = pd.read_csv('diabetes.csv')

In [6]:
df.sample(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
560            6      125             76              0        0  33.8   
762            9       89             62              0        0  22.5   
129            0      105             84              0        0  27.9   
55             1       73             50             10        0  23.0   
23             9      119             80             35        0  29.0   

     DiabetesPedigreeFunction  Age  Outcome  
560                     0.121   54        1  
762                     0.142   33        0  
129                     0.741   62        1  
55                      0.248   21        0  
23                      0.263   29        1

In [17]:
X = df.drop(['Outcome'], axis=1).values
Y = df['Outcome'].values

In [19]:
X.shape

(768, 8)

In [20]:
Y.shape

(768,)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, random_state=2)

In [24]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(X_train,Y_train)

LinearRegression()

In [25]:
print(X_train.shape)
print(X_test.shape)

(614, 8)
(154, 8)


In [27]:
Y_pred = mlr.predict(X_test)

In [28]:
from sklearn.metrics import r2_score

In [30]:
r2_score(Y_test, Y_pred)

0.19119337815403292

In [32]:
mlr.coef_

array([ 0.02604481,  0.00636631, -0.00238738,  0.00072783, -0.00022277,
        0.01275374,  0.16008617,  0.00127011])

In [34]:
mlr.intercept_

-0.8702366919117843

In [36]:
class own_LR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [37]:
my_mlr = own_LR()

In [43]:
my_mlr.fit(X_train, Y_train)

In [45]:
X_train.shape

(614, 8)

In [47]:
np.insert(X_train,0,1,axis=1).shape

(614, 9)

In [48]:
y_pred = my_mlr.predict(X_test)

In [49]:
y_pred

array([ 1.90462826e-03,  2.39429343e-01,  1.10562272e-01,  3.11236987e-01,
        5.70174319e-01,  1.50343359e-01,  5.37976118e-02,  4.58059182e-01,
        4.81570449e-04,  5.49684168e-01,  4.03355822e-01,  4.30315206e-01,
        6.58903961e-01,  2.42115626e-01, -1.49374524e-01,  7.53330954e-01,
        8.07481119e-01, -6.07681249e-02,  3.16057021e-01,  8.52796982e-01,
        9.83320931e-01,  7.56821710e-01,  1.60464626e-01,  4.31005605e-01,
        1.13813261e-01,  4.87510105e-02,  5.78379810e-01,  4.25668664e-01,
        2.39461800e-01,  3.34672688e-01,  3.14173416e-01,  4.42232972e-01,
       -2.26999855e-01,  2.91254808e-01,  4.01255479e-01,  1.03437687e+00,
        3.72530667e-01,  7.22801124e-01,  3.49484092e-01,  2.25941837e-02,
        2.43506139e-01,  8.88253011e-02,  4.49445701e-01,  2.45962179e-01,
       -7.70729226e-02, -2.10660582e-02,  3.06661242e-01,  4.43499558e-01,
        1.24883978e-01,  4.24915795e-01,  1.30895173e+00,  1.50886052e-01,
        4.16533644e-01,  

In [52]:
r2_score(Y_test,Y_pred)

0.19119337815403292

In [84]:
my_mlr.coef_

array([ 0.02604481,  0.00636631, -0.00238738,  0.00072783, -0.00022277,
        0.01275374,  0.16008617,  0.00127011])

In [59]:
my_mlr.intercept_

-0.8702366919117682